### ISSUE TITLE
Release a new version (with bumped graceful-fs dependency)

### ISSUE THREAD

**Issue by ChALkeR** [gobblejs/gobble#100]
`graceful-fs` versions lower than v4 reevaluate native `fs` module source, which is not supported.
You should update your `graceful-fs` dependency to v4 or later. 

It is already updated in the current master, but no new version has been released yet, so the current version still uses old `graceful-fs`.

Tracking issue: https://github.com/nodejs/node/issues/5213.

**Comment by heavyk** [comment]
master uses graceful-fs@4.x already (though it's probably not published).

however, one of the dependencies (sander) does not yet either: https://github.com/Rich-Harris/sander/pull/7

**Comment by Rich-Harris** [comment]
Just released 0.11.0 with all dependencies up to date – thanks, and sorry for the long wait
