### ISSUE TITLE
Have a way to "growl" from plugins

### ISSUE THREAD

**Issue by julienw** [gobblejs/gobble#101]
Currently a plugin can growl by itself (by importing node-growl or node-notifier); but it would be useful to have a more generic way to growl:
* send one notification per build instead of one per plugin per build
* have a global way to disable/enable the notifications

**Comment by Rich-Harris** [comment]
Great idea, thanks! I think this probably belongs to the CLI rather than to Gobble itself, so I've opened https://github.com/gobblejs/gobble-cli/issues/21 – will close this in favour of that.
