### ISSUE TITLE
Can directory transformers also have defaults?

### ISSUE THREAD

**Issue by fskreuz** [gobblejs/gobble#102]
> `options` is an object. it is shallow-cloned from the user-supplied options object (if none is supplied, it will be created as `{}`), so you can modify it safely
> https://github.com/gobblejs/gobble/wiki/Writing-plugins#directory-transformers

There's no mention of defaults like the one in file transformers

> `options` is shallow-cloned from the user-supplied options (**plus the defaults, if specified.** User options override defaults)
> https://github.com/gobblejs/gobble/wiki/Writing-plugins#file-transformers

Would it be possible to provide defaults to directory transformers in the same manner as file transformers?

**Comment by heavyk** [comment]
also a one-liner. :)

**Comment by Rich-Harris** [comment]
Released as 0.11.0, thanks both!
