### ISSUE TITLE
Is there a way to skip creation of a file with a file transformer?

### ISSUE THREAD

**Issue by fskreuz** [gobblejs/gobble#103]
Was thinking of something like

```js
function transform(contents, options){
  // parsing
  return contents.something ? parsedContents : null;
}
```

Where `null` would tell gobble to *not* create the resulting file. It's possible with directory transformers but it's a ton of code to write at times, especially when the files are just `1:1`.

**Comment by heavyk** [comment]
hey dude, this is a one-liner so I did it just now

**Comment by fskreuz** [comment]
I thought I'd leave it out here for a bit while longer. Was thinking

- `null` might actually be a valid return value.
- Are there any other ways to indicate that this 1:1 operation shouldn't write the output.

**Comment by heavyk** [comment]
null is not a valid return value. inside of a file, you could have the string "null" and you would see those letters inside. but, like node dictates, a file can either be a utf-8 encoded string or a buffer. right now gobble only checks to see if it's a string, but it should also check to see if a buffer is returned. (I'll add that to the PR shortly)

anyway, I thought null was a good idea to skip the file. it is useful.

**Comment by Rich-Harris** [comment]
In 0.11.0 :+1:
