### ISSUE TITLE
node v6 graceful-fs warning

### ISSUE THREAD

**Issue by martypdx** [gobblejs/gobble#113]
upgraded to node v6 and this little fortune cookie started showing up:

```sh
> gobble

(node:5438) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
gobble: server listening on port 4567                                           
gobble: livereload server running                                                        
...
```

**Comment by IvanSanchez** [comment]
Isn't this rather a `sander` issue?

**Comment by fskreuz** [comment]
Possible duplicate of https://github.com/gobblejs/gobble/issues/111

**Comment by Rich-Harris** [comment]
Are you using the most recent gobble and gobble-cli? That fixed the warning for me – both are using latest graceful-fs

**Comment by martypdx** [comment]
> Are you using the most recent gobble and gobble-cli?

I thought I had, *sigh*
