### ISSUE TITLE
Watchers for everybody

### ISSUE THREAD

**Issue by TrySound** [gobblejs/gobble#114]
Hi. I saw issues about chokidar performace and here's my thoughts
- pathwatcher sucks because depends on python. Not everybody has an access to python
- chokidar seems good last half yeah. Didn't see performance problems on windows even with native mode (not polling).

So, maybe gobble could revert temporary replacement and everybody will be happy :)

**Comment by IvanSanchez** [comment]
Right now `pathwatcher` is creating a lot of issues in my CI flows, as the `runas` dependency fails to re-compile every time.

You're not alone in the `pathwatcher` criticism - there's #108, #115 and #106. According to #92, `pathwatcher` *should* be more solid than `chokidar`, and the project has gone with that so far. I wonder if there's enough reason to go back to chokidar, though.

**Comment by sod** [comment]
There is also https://github.com/amasad/sane ... e.g. used by jspm :)

**Comment by evs-chris** [comment]
FWIW I'm super :+1: on getting a fresh version of gobble without pathwatcher out. CI does _not_ like pathwatcher, so we're sticking with an older gobble for now. :smile: It _looks_ like it's already been swapped out in master.

**Comment by teehemkay** [comment]
Same here.:+1: on removing pathwatcher  since it fails to compile on too many enviromments

**Comment by Rich-Harris** [comment]
Just released 0.12 with all the accumulated changes (on which note – wow! Sorry, I totally dropped the ball, I don't deserve such good open source friends) including switching back to chokidar, to see if things are any better. Still having a bit of trouble getting stuff to build on Node 7, but hopefully it will fix something...

**Comment by teehemkay** [comment]
Thanks Rich! I'll try 0.12 at work on Monday.
