### ISSUE TITLE
Documentation for #include and #exclude looks reversed

### ISSUE THREAD

**Issue by joshbedo** [gobblejs/gobble#35]
Was just reading through the documentation and noticed this. Is this correct? Include: Filters out any files that don't match the pattern.. wouldn't that be exclude?

![](https://api.monosnap.com/rpc/file/download?id=IDUC3fwQiRSgHbKAWuoBRVMndgC6F9)

If you want i can put up a PR :)

**Comment by Rich-Harris** [comment]
Ha, it's actually correct, just a very confusing sentence! It's including the files that match the pattern by excluding the files that don't match the pattern... I've reworked the sentence to eliminate the weird double negative. Thanks
