### ISSUE TITLE
Fix crazy logging output in Travis CI (and other places, probably)

### ISSUE THREAD

**Issue by Rich-Harris** [gobblejs/gobble#59]
Not sure if it's even possible to fix, but it would be cool to prevent this sort of garble:

![screen shot 2015-04-22 at 4 31 39 pm](https://cloud.githubusercontent.com/assets/1162160/7284658/32161494-e90d-11e4-8467-1747c0ca6001.png)

**Comment by mohsen1** [comment]
npm has the `/` `|` `\` spinner that is annoying in the same way. For npm you can run `npm config set spin=false` to disable it. I guess you can have an option to turn off animations in CI environment. It would be nice if it disable itself when it sees `TRAVIS` or `CIRCLECI` in the PATH.

**Comment by martypdx** [comment]
If React can do iOS, we can surely tackle RactiveConsole. :bomb:  walking away from the keyboard

**Comment by Rich-Harris** [comment]
@martypdx not until we've released an [oscilloscope compatible](https://www.youtube.com/watch?v=aMli33ornEU) version

@mohsen1 that's a great idea, thanks - I've implemented it via https://github.com/Rich-Harris/stevedore/commit/1cb0eda8a505c6949febe1386b1e0546fd42c41e. It checks for `process.env.CI === 'true'`, apparently that's a common thing among CI tools.
