### ISSUE TITLE
Question - global gobble?

### ISSUE THREAD

**Issue by timshannon** [gobblejs/gobble#61]
The documentation implies (although I may be misunderstanding) that you should install gobble globally `npm install -g gobble-cli` , but after installing globally I can't run my gobblefile as I get this error: 

`gobble: could not find a local copy of gobble. You should probably install it with npm install --save-dev gobble`

Should it be run locally or globally?

**Comment by evs-chris** [comment]
A little of both. The CLI can be installed globally for easy access to the `gobble` command in your shell. It, in turn, need access to a copy of gobble (the main guts of the tool as a library) to actually do the building.

You could install gobble globally too, but that's generally frowned upon from what I've seen in the node community, as it would tie multiple projects to one version of the lib where updates may break things in weird ways.

You can also just install the CLI locally and use an npm script entry to call it if you'd like to avoid globals entirely.

**Comment by timshannon** [comment]
Makes sense. Thanks,

**Comment by Rich-Harris** [comment]
> You can also just install the CLI locally and use an npm script entry to call it if you'd like

I've found myself doing that more and more - adding gobble-cli as a `devDependency` alongside gobble itself, then adding

```js
"scripts": {
  "start": "gobble",
  "build": "gobble build -f dist"
}
```

to the `package.json` so that anyone can serve/build the project with `npm start` or `npm run build`. Makes everything a bit more friendly and resilient

**Comment by martypdx** [comment]
I'm posting this here because it seems related. I set up a new project and latest gobble-cli installed fine, but I get this message:

```sh
> gobble

gobble: Your locally installed gobble version (0.7.4) is out of date, and may
        cause problems with gobble-cli. You should update with npm update 
        gobble                                                            
gobble: server listening on port 4567  
...
```

Okay, but I can't find an installed gobble:

```sh
~/cardsmith/cardfire>npm ls gobble
cardfire@0.1.0 /Users/marty/cardsmith/cardfire
└── (empty)

~/cardsmith/cardfire>npm ls gobble -g
/Users/marty/npm/lib
└── (empty)
```

So if I try to explicitly install it:

```sh
~/cardsmith/cardfire>npm install gobble --save-dev
npm WARN package.json cardfire@0.1.0 No repository field.
npm ERR! addLocal Could not install gobble
npm ERR! Error: ENOENT, open 'gobble/package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "gobble" "--save-dev"
npm ERR! cwd /Users/marty/cardsmith/cardfire
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.5.0-alpha-3
npm ERR! path gobble/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
```

But I'm not using `/usr/local` for node:

```sh
~>which gobble
/Users/marty/npm/bin/gobble
~>
```

Sorry if this is my node problem. But confused about where the heck gobble is...

**Comment by Rich-Harris** [comment]
@martypdx woah, looks odd. Though I can't make heads or tails of npm error messages at the best of times. Did you `npm link gobble` at any point? I think that has the effect of *sort of* making it globally installed - maybe there's something funky going on with symlinks?

**Comment by timshannon** [comment]
Do you have your `NODE_PATH` enviroment variable set to something?

`echo $NODEPATH`

**Comment by martypdx** [comment]
I was running older version of node and npm and time for update anyway. I had different things pointing different places. It was time to `rm -rf` and start anew. Gobble running fine, except I've got a gobble-sass transform and I'm getting this in the gobble build:

```sh
build invalidated (1 file changed). restarting                     
gobble: 11-sassFile done in 3ms                                        
gobble: 12-esperanto done in 4ms                                       
gobble: 13-es6transpiler done in 3ms                                   
gobble: 14-makeComponent done in 2ms                                   
gobble: 15-ractive done in 8ms                                         
gobble: 16-merge done in 6ms                                           
gobble: 17-browserify done in 1699ms                                   
gobble: 18-include done in 1ms                                         
gobble: 19-merge done in 8ms                                           

gobble: ENOENT, open '/Users/marty/cardsmith/cardfire/.gobble/min.css.map *'   
>>>
Error: ENOENT, open '/Users/marty/cardsmith/cardfire/.gobble/min.css.map *'
    at Error (native)
<<<

gobble: build completed in 1750ms. Listening for changes...
```

(Yes, time to update to babel too...)

**Comment by Rich-Harris** [comment]
Ooh, I saw an error like that as well recently, and sort of glossed over it (was busy), but looking at it now I would bet that it's due to a faulty `sourceMappingURL` regex - whereas JS sourcemap comments look like this...

```js
//# sourceMappingURL=app.js.map
```

...CSS sourcemap comments look like this:

```css
/*# sourceMappingURL=styles.css.map */
```

So the trailing `*` is being picked up, and the filename is wrong, hence `ENOENT`. 

Half of me is glad that gobble 0.8+ flattens sourcemap chains automatically, because a) it forces these issues into the open, b) makes dealing with sourcemaps a good bit easier when it works, and c) ought to present some interesting optimisation opportunities. The other half wants to punch me in the face repeatedly

**Comment by Rich-Harris** [comment]
@martypdx Working through some more sourcemap stuff today... at the very least the CSS sourcemap error is now fixed. If you reinstall gobble (or update sorcery within gobble) that error should no longer appear
