### ISSUE TITLE
Default with accept with regex doesn't transform to .ext

### ISSUE THREAD

**Issue by martypdx** [gobblejs/gobble#97]
Bit of an edge case, but given file transformer defaults like:

```js
someTransformer.defaults = {
	accept: /\..*/,
	ext: '.js'
};
```

Output won't get mapped correctly because [this line](https://github.com/gobblejs/gobble/blob/a667fdcab8d4a4021fc4aa29ced173f61dbac48a/src/builtins/map.js#L32):

```js
const destname = ( options.ext && ~options.accept.indexOf( ext ) ) ? ...  : ... ;
```

is doing an `indexOf` check so regex fails

**Comment by Rich-Harris** [comment]
fixed in 0.11.3 👍
