### ISSUE TITLE
Plugin request: cssmin/clean-css

### ISSUE THREAD

**Issue by fskreuz** [gobblejs/gobble#98]
Not really sure where to put this, but it would be handy to have.

For project-controlled styles, I use SASS and the `outputStyle: 'compressed'` setting which is fine. But...

- There are libs that only ship with `.css`.
- Some use another preprocessor for their source (like LESS) which I can't import.
- Importing `.css` into SASS falls back to regular CSS imports, and paths are terrible because libs are from npm (paths will start with `node_modules`).

There's no other option but to concat the dist `.css` then minify.

**Comment by MartinKolarik** [comment]
I wrote [gobble-clean-css](https://www.npmjs.com/package/gobble-clean-css) a while back. Guess that's what you were looking for?

**Comment by fskreuz** [comment]
(facepalm) should have used npm's search. I was looking at gobble's github. Thanks!
