### ISSUE TITLE
code example for 'task = node.build'?

### ISSUE THREAD

**Issue by jamesjensen88** [gobblejs/gobble#99]
I need to trigger gobble build from a Node script, and saw [this].(https://github.com/gobblejs/gobble/wiki/API-reference#task--nodebuild-options-)

Could anyone provide a code example?

**Comment by Rich-Harris** [comment]
Don't know if this is still relevant – sorry – but you can use Gobble programmatically like so:

```js
var node = require( './gobblefile.js' );

var task = node.build({
  dest: 'build'
});

task.then( function () {
  console.log( 'finished!' );
});
```
